### ISSUE TITLE
The test methods are not printed in order in the junit report

### ISSUE THREAD

**Issue by kiranchitturi** [ftobia/pytest-ordering#11]
Hi,

I have been using pytest-ordering and it works/fits my usecase. Thank you for providing this plugin.

Whenever I generate the junit xml report, the tests are not in order they are executed in the report. Is it possible to re-order based on the order they are executed ?

**Comment by ftobia** [comment]
I'm willing to accept PRs for the above behavior, but I don't plan on tackling it myself.
