### ISSUE TITLE
pytest.mark.order1 doesn't work after updating from 0.3 to 0.4

### ISSUE THREAD

**Issue by maticrivo** [ftobia/pytest-ordering#19]
After updating to pytest-ordering version 0.4 the ordering stopped working

**Comment by ftobia** [comment]
:-/ Sorry about this.

I think I'd like to deprecate the "orderN" markers in favor of "run(order=1)" -- but since you are already using the former, I'm interested in your opinion.

At the very least, the documentation is now incorrect.

**Comment by maticrivo** [comment]
i think "run(order=1)" looks better, i already changed my tests to use it, so if you feel like deprecating the "orderN" go ahead, just make sure you change documentation accordingly :)

Thanks!

**Comment by ftobia** [comment]
This was in develop branch. Now 0.5 is released.
