### ISSUE TITLE
Ordering a non-continuous segment causes no ordering to happen

### ISSUE THREAD

**Issue by MikeSandford** [ftobia/pytest-ordering#23]
I've got a number of py.test suites written that test various aspects of a system.  One file might have a few dozen tests in it, grouped logically.  The next file might have only a dozen.  The next might have a hundred or more.

I'd like to run file1 before file2 before file3, and I absolutely NEED to run the tests inside file1 in a particular order, and the tests inside file2 in a particular order, and same for file3.  So if I start file1 at pytest.mark.run(order=1000) , then 1001, 1002, etc, and file2 at pytest.mark.run(order=2000) and file3 at pytest.mark.run(order=3000) I naively thought that this would result in 1000, 1001, 1002, etc then 2000, 2001, etc, 3000, 3001, etc all getting run in order of increasing order number.

But I'm not seeing that behavior at all when I run the tests as a suite.  In order to get the files to execute in the correct order I've used a script to run py.test on each one of them individually.  And that seemed to work on the files starting at order=1000 or order=2000.  But now that I've got a file starting at order=3000,  I'm seeing strange behavior where instead of

[3000,3001,30002,3003,3004,3005,3006,3007,3008,3009,3010,3011]

I'm instead seeing 

[3008,3009,3010,3011,3000,3001,30002,3003,3004,3005,3006,3007]

I took a peek in https://github.com/ftobia/pytest-ordering/blob/develop/pytest_ordering/__init__.py but it wasn't immediately obvious to me what was getting done where.  I'll probably take another look after I post this to see if I can't put together a pull request, but I'm definitely puzzled.

The main reason I would like this out-of-order business is so that if I add a couple of tests to the end of one file I don't have to go reset the ordering of every other file (by hand!) to make room in the perfectly ordered number line.

**Comment by ftobia** [comment]
Interesting use case. I think a feature that would enable your request is to allow ordering of (all tests within a) test file. So like you could mark a whole file as `run(order=1)` or equivalent, which would cause all tests in that file to run first, then all tests in all the other files as normal. Does this sound like what you want?

This sounds similar to #20 where there would be different "scopes" for ordering, like session, class, module.

I admit the pytest-ordering internals are a bit inscrutable. Implementing #20 would be a pretty big refactoring, I think. Good luck. I'll try to put some time and effort into this project over the next few weeks.

**Comment by mlaurie** [comment]
This issue produces all sorts of weird behavior currently.

Things will stay in order, up to a certain point of non-continuous ordering (i'm not sure what's triggering the change yet).
eg1: order 1-3, 5-7 (this orders properly)
eg2: order 1-3, 10-12 (this doesn't order properly)

**Comment by MikeSandford** [comment]
Lexical ordering instead of integer ordering, perhaps?

**Comment by Bengreen** [comment]
i had similar problems.
I was using non-contiguous order numbers as i am expecting to have to insert additional tests between the current ones in the future so having numbering separated by 5 or 10 makes sense.
I took a spin at rewriting part of the functions to capture this and am testing at moment. Hopefully you get the pull request soon.

**Comment by ftobia** [comment]
I believe this is issue is addressed by #26

**Comment by ftobia** [comment]
This was in develop branch. Now 0.5 is released.
