### ISSUE TITLE
Run tests in order of definition

### ISSUE THREAD

**Issue by kyeett** [ftobia/pytest-ordering#34]
Hello!

I wanted to run my tests in the order they are defined, rather than having to define every step myself. Is there some other way of achieving this, or **would this be a useful addition to the module?**

    class Order:
        i = 1500

        @staticmethod
        def auto():
            Order.i +=  1
            return Order.i

Then I can add the following tag to all tests:
        
    @pytest.mark.run(order=Order.auto())

**Comment by ftobia** [comment]
I believe that's pytest's default behavior. Tests are run top-to-bottom within a file.

**Comment by ftobia** [comment]
I am closing this ticket since I believe the described behavior is pytest's default behavior. Please re-open as appropriate.
