### ISSUE TITLE
support for python 3.6

### ISSUE THREAD

**Issue by yunqu** [ftobia/pytest-ordering#35]
It seems that the pytest ordering does not work with python 3.6. Is it possible to support this package for python 3.6?

**Comment by ftobia** [comment]
The tests pass for me locally on python 3.6. What error message are you seeing?

**Comment by yunqu** [comment]
I have been trying this:

```python
import pytest

@pytest.mark.order2
def test_b():
    assert True

@pytest.mark.order1
def test_a():
    assert True

import pytest

@pytest.mark.order4
def test_d():
    assert True

@pytest.mark.order3
def test_c():
    assert True
```

Then run py.test -vsrw, I see the outcome is "b a d c", while the correct output is expected to be "a b c d".

**Comment by yunqu** [comment]
I think the problem is now solved.

**Comment by ftobia** [comment]
Thanks. I'm guessing it was the bug in 0.4 where it relied on an implementation detail of how dicts with small integer keys were sorted.
