### ISSUE TITLE
No matching distribution found for pytest-ordering

### ISSUE THREAD

**Issue by klaxmi361** [ftobia/pytest-ordering#40]
below error when im trying to install the package

python version : 2.7

Collecting pytest-ordering
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109fbb250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /artifactory/api/pypi/python/simple/pytest-ordering/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109fbb2d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /artifactory/api/pypi/python/simple/pytest-ordering/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109fc1290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /artifactory/api/pypi/python/simple/pytest-ordering/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109fc1a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /artifactory/api/pypi/python/simple/pytest-ordering/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109fc1d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /artifactory/api/pypi/python/simple/pytest-ordering/
  Could not find a version that satisfies the requirement pytest-ordering (from versions: )
No matching distribution found for pytest-ordering

**Comment by ftobia** [comment]
I cannot reproduce this. From the traceback it looks like your pip configuration is pointing to an artifactory repo. If that's the case, and if the pytest-ordering package isn't available in your artifactory repo, then it won't be able to find the package.

Try: `pip install --index-url https://pypi.python.org/simple pytest-ordering` assuming you have access to the internet and pypi.python.org. If that works I'm betting it's a problem with your pip setup.

**Comment by klaxmi361** [comment]
working as expected with `pip install --index-url https://pypi.python.org/simple pytest-ordering`
