### ISSUE TITLE
RemovedInPytest4Warning: MarkInfo objects are deprecated

### ISSUE THREAD

**Issue by kradem** [ftobia/pytest-ordering#43]
Hi everybody!

Could someone update code regarding this warning:

    /home/kradem/.virtualenvs/myenv/lib/python3.6/site-packages/pytest_ordering/__init__.py:54: 
    RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are 
    hard to deal with correctly.
    Please use node.get_closest_marker(name) or node.iter_markers(name).
    Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
      order = mark.kwargs.get('order')

**Comment by ftobia** [comment]
Fixed in 0.6 release.
