### ISSUE TITLE
pytest_ordering-0.5-py3-none-any.whl (25.X.2018) is invalid (probably it is 0.6.0 version)

### ISSUE THREAD

**Issue by MiroslawBernat** [ftobia/pytest-ordering#46]
Hi!
Please, remove this wheel from pypi (uploaded 28.X.2018), because it is invalid (probably it is wheel from 0.6.0 version). My pytest's tests just blew up, because of `mark = item.get_closest_marker(mark_name)` (__init__.py, line 45). I'm using pytest 3.2.5 and with old 0.5.0 was working OK.
Regards
Miroslaw

**Comment by ftobia** [comment]
Sorry about that! I have deleted it.

**Comment by ftobia** [comment]
Please re-open if you are still seeing this issue.

**Comment by MiroslawBernat** [comment]
It's OK now, thanks! Thankfully, even my devpi server forgot about the unnecessary wheel :)
Thanks for quick reaction!
