### ISSUE TITLE
it is not running in order

### ISSUE THREAD

**Issue by nadim1975** [ftobia/pytest-ordering#47]
![pytest order](https://user-images.githubusercontent.com/42757588/47747014-bf0a6980-dc5d-11e8-8fde-a024c9e7d8e0.png)

in the above test it should print in this order A,B, E,D,C

but it is still printing as A,B,C,D,E

**Comment by andyg0808** [comment]
It looks like the `order` argument got misspelled as `oreder`. Perhaps that is the problem?

**Comment by ftobia** [comment]
Looks like this isn't actually a bug. If anyone disagrees, please re-open.
