### ISSUE TITLE
Version 0.6 can not be installed from pypi

### ISSUE THREAD

**Issue by ghost** [ftobia/pytest-ordering#49]
Hi,

I am getting pytest warnings because I can not install version 0.6 from pypi.

From linux (centos, python2.7), I have run `pip install pytest-ordering` and I got the version 0.5.

When I try to install the version 0.6 from the command line:
`pip install pytest-ordering==0.6`

I am getting an error: Could not find a version that satisfies the requirement ...

Any idea ?

Thanks

**Comment by ftobia** [comment]
Try it now. It seems that earlier I had only uploaded a python3 wheel.
Now I have uploaded a source distribution and a python2 wheel. You should be able to install pytest-ordering 0.6.

Let me know if it's still not working for you.

**Comment by ghost** [comment]
It works!

Thanks :)
