### ISSUE TITLE
register custom marks

### ISSUE THREAD

**Issue by brianmaissy** [ftobia/pytest-ordering#54]
The pytest [documentation recommends](https://docs.pytest.org/en/latest/writing_plugins.html#registering-markers) that plugins register all of their warnings, and since pytest 4.5.0 running tests decorated with unregistered marks emits a [PytestUnknownMarkWarning](https://github.com/pytest-dev/pytest/issues/4826).

I'm happy to open a PR if that sounds ok.

**Comment by ftobia** [comment]
That sounds good to me, I'm happy to accept PRs for this.

At the risk of some scope creep for you, while you're in there, would you mind taking a look at ways of running the tests (via TravisCI) against pytest 3.x and 4.x? It's something I haven't kept up on, and e.g. I'd want to make sure that the marker registration doesn't break on earlier versions, or if it does and there's no good way around it, explicitly drop support for earlier versions of pytest. That's the only thing I can see holding up a PR like this.

**Comment by brianmaissy** [comment]
Sure, I'll take a look. By 3.x and 4.x you mean you want to check against the latest 3.x and the latest 4.x, or on all of the versions: [3.1, 3.2, ... 3.10, 4.0, ...] ?

**Comment by ftobia** [comment]
More versions are better to test if possible, but I'll settle for just the latest 3.x release and latest 4.x release. I'll trust your judgment if for example you get in there and it's infeasible for whatever reason.

**Comment by brianmaissy** [comment]
It looks like currently pytest-ordering only works on pytest 3.6 and higher, because of the usage of [get_closest_marker](https://docs.pytest.org/en/latest/changelog.html#id441). Do we want to test only on pytest 3.6 and above (and officially drop support), or fix the backwards compatibility? Related: https://github.com/ftobia/pytest-ordering/issues/48

And if the answer is dropping the support for pytest < 3.6, then since pytest [dropped support](https://docs.pytest.org/en/latest/changelog.html#id586) for python 2.7 and python 3.3 in pytest 3.3, then we should too.

In any case I'll take the opportunity to formalize the supported versions of python and pytest, both in the docs and in setup.py.
