### ISSUE TITLE
I would like to nominate myself for a maintianer of this repository. 

### ISSUE THREAD

**Issue by rajibmitra** [ftobia/pytest-ordering#60]
I would like to nominate myself for a maintianer of this repository.

**Comment by ftobia** [comment]
Thanks for your interest! A maintainer would ideally be familiar with codebase and comfortable making changes and adjudicating bug reports and feature requests. Could you try tackling one or two bugs or feature requests?

**Comment by rajibmitra** [comment]
Sure, I would like tackle this one https://github.com/ftobia/pytest-ordering/issues/58 , so here I can see its not honoring the depends=['test_a'] statement, so in my opition it shoud check where is the test_a and execute it first then the next test case should execute. I will take a look at the code.

**Comment by rajibmitra** [comment]
same thought as this one , I would like to implement this here in pytest-ordering 
https://gist.github.com/ftesser/4919ac83ad9e912e72e8a532d7ef6504
