### ISSUE TITLE
How to make the order decorator take effect only within the test module, not globally？

### ISSUE THREAD

**Issue by Northxw** [ftobia/pytest-ordering#78]
I read the plugin documentation，then I went to experience it, I found a problem, if I use the order decorator in the test module, and then run all the test modules, the test method decorated with order will be executed first.

In fact, my idea is that when running all test modules, the test method using the order decorator only takes effect within a single module. How can I achieve this?

Looking forward to your answer, thank you very much. 🙇‍

**Comment by mrbean-bremen** [comment]
This is by design. The ordering in `pytest-ordering`  is always global. If you use the successor project `pytest-order` (mentioned in the Readme), you can use the command line option `--order-scope=module` to get the wanted behavior.

**Comment by Northxw** [comment]
Thank you very much for your reply

**Comment by Northxw** [comment]
solved
