### ISSUE TITLE
Allow ordering within a "group"

### ISSUE THREAD

**Issue by ftobia** [ftobia/pytest-ordering#8]
Allow custom markers to define a "group" when you use ordering keywords, for example:

    @pytest.mark.foo(order=2)
    def bar():
        pass

    @pytest.mark.foo(order=1)
    def baz():
        pass

The above example will ensure that `baz()` runs before `bar()`. The group `foo` will itself not be ordered with respect to other tests.

**Comment by ftobia** [comment]
I decided I don't like this idea. Though if anyone else does like it, I'm willing to be convinced.

**Comment by adnanmuttaleb** [comment]
Groups make sense, for example: If you have an API with set of endpoint, you may mark each endpoint as group and impose ordering within each group as:

1. Test POST
2. Test PUT 
3. Test DELETE 
(GET may be placed anywhere) 

Also we may implement groups similarly to fixtures, in other words, test cases may be ordered in class level, module level, package level or in session level.

**Comment by adnanmuttaleb** [comment]
Are you convinced?, if yes I may submit a PR for this feature.
